language: go

go:
  - "1.12.6"

services:
  - docker

script:
  - make build_linux
  - make test
  - make build_images
  - make validate_client_proxy

deploy:
  - provider: script
    script: make upload_image
    on:
      branch: makefile_fix

  - provider: script
    script: make upload_private_image
    on:
      branch: makefile_fix
